<!DOCTYPE html>
<html lang="en">
<head>
  <title>Home - Home Page | Design Company - Free Website Template from Templatemonster.com</title>
  <meta charset="utf-8">
  <link rel="stylesheet" href="<?php echo $this->BaseUrl(); ?>/gmc/css/reset.css" type="text/css" media="all">
  <link rel="stylesheet" href="<?php echo $this->BaseUrl(); ?>/gmc/css/reset.css" type="text/css" media="all">
  <script type="text/javascript" src= "<?php echo $this->BaseUrl(); ?>/gmc/js/jquery-1.4.2.min.js" ></script>
  <script type="text/javascript" src= "<?php echo $this->BaseUrl(); ?>/gmc/js/cufon-yui.js"></script>
  <script type="text/javascript" src= "<?php echo $this->BaseUrl(); ?>/gmc/js/Humanst521_BT_400.font.js"></script>
  <script type="text/javascript" src= "<?php echo $this->BaseUrl(); ?>/gmc/js/Humanst521_Lt_BT_400.font.js"></script>
	<script type="text/javascript" src= "<?php echo $this->BaseUrl(); ?>/gmc/js/roundabout.js"></script>
  <script type="text/javascript" src= "<?php echo $this->BaseUrl(); ?>/gmc/js/roundabout_shapes.js"></script>
  <script type="text/javascript" src= "<?php echo $this->BaseUrl(); ?>/gmc/js/gallery_init.js"></script>
  <script type="text/javascript" src= "<?php echo $this->BaseUrl(); ?>/gmc/js/cufon-replace.js"></script>
  <!--[if lt IE 7]>
  	<link rel="stylesheet" href="css/ie/ie6.css" type="text/css" media="all">
  <![endif]-->
  <!--[if lt IE 9]>
  	<script type="text/javascript" src="js/html5.js"></script>
    <script type="text/javascript" src="js/IE9.js"></script>
  <![endif]-->
</head>

<body>
  <!-- header -->
  <header>

    <div class="container">
    	<h1><a href="<?php echo $this->BaseUrl(); ?>/index/accueil">Game Center</a></h1>
      <nav>
        <ul>
        	<li><a href="<?php echo $this->BaseUrl(); ?>/accueil" class="current">Homr</a></li>
          <li><a href="<?php echo $this->BaseUrl(); ?>/about"> About</a></li>
          <li><a href="<?php echo $this->BaseUrl(); ?>/category">Favorite</a></li>
          <li><a href="<?php echo $this->BaseUrl(); ?>/favorite">Favorite</a></li>
          <li><a href="<?php echo $this->BaseUrl(); ?>/contacts">Contact</a></li>
          <li><a href="<?php echo $this->BaseUrl(); ?>/sitemap">Sitemap</a></li>
        </ul>
      </nav>
    </div>
	</header>

  <!-- /#gallery -->
  <div class="main-box">
    <div class="container">
      <div class="inside">
        <div class="wrapper">
<br><br><br><br><br><br><h2>hna radi ikon jeux</h2><br><br><br><br><br><br><br><br><br><br><br><br>
        </div>
      </div>
    </div>
  </div>
  <!-- footer -->
  <footer>
    <div class="container">
    	<div class="wrapper">
        <div class="fleft">Copyright - Zakaria&Sara</div>
        <div class="fright"><a rel="nofollow" href="http://www.templatemonster.com/" target="_blank">Website template</a> designed by TemplateMonster.com&nbsp; &nbsp; |&nbsp; &nbsp; <a href="http://templates.com/product/3d-models/" target="_blank">3D Models</a> provided by Templates.com</div>
      </div>
    </div>
  </footer>
  <script type="text/javascript"> Cufon.now(); </script>
</body>
</html>
