<div class="play-btn-wrapper">
                                   <a href="/play/bigpoint/drakensang-online" class="playLink play-btn " data-promo="home+-+index+-+DL+-+play+now" data-beacon="{&quot;p&quot;:{&quot;lnid&quot;:&quot;sec1_lnk3&quot;}}">
                                       <span class="button-text">Play Now</span>
                                   </a>
                        </div>